Repository logical-mechanism/Seedelf-Wallet, pull requests merged in 2024-12, with the labels that each got.

#27 good pass on the readmes
  README.md
  RELEASE.md
  happy-path-scripts/.env
  happy-path-scripts/.env.mainnet
  happy-path-scripts/.env.preprod
  happy-path-scripts/.env.sancho
  happy-path-scripts/.gitignore
  happy-path-scripts/00_createScriptReferences.sh
  happy-path-scripts/README.md
  happy-path-scripts/all_balances.sh
  happy-path-scripts/create_wallet.sh
  happy-path-scripts/data.file
  happy-path-scripts/data/exe_units.json
  happy-path-scripts/data/path_to_cli.sh
  happy-path-scripts/data/path_to_socket.sh
  happy-path-scripts/data/pointer/metadata.json
  happy-path-scripts/data/pointer/pointer-redeemer.json
  happy-path-scripts/data/wallet/change-wallet-datum.json
  happy-path-scripts/data/wallet/receiver-wallet-datum.json
  happy-path-scripts/data/wallet/wallet-datum.json
  happy-path-scripts/data/wallet/wallet-redeemer.json
  happy-path-scripts/seedelf/.gitignore
  happy-path-scripts/seedelf/00_checkBalance.sh
  happy-path-scripts/seedelf/01_createAddress.sh
  happy-path-scripts/seedelf/02_burnAddress.sh
  happy-path-scripts/seedelf/03_sendToSeedElf.sh
  happy-path-scripts/seedelf/04_spendFunds.sh
  happy-path-scripts/seedelf/backend/.gitignore
  happy-path-scripts/seedelf/backend/__init__.py
  happy-path-scripts/seedelf/backend/bls12_381.py
  happy-path-scripts/seedelf/backend/find.py
  happy-path-scripts/seedelf/backend/requirements.txt
  happy-path-scripts/seedelf/backend/setup.sh
  happy-path-scripts/seedelf/backend/tx_simulation.py
  happy-path-scripts/seedelf/backend/value.py
  happy-path-scripts/seedelf/backend/wallet.py
  happy-path-scripts/seedelf/query.sh
  happy-path-scripts/send_all.sh
  happy-path-scripts/submit_tx.sh
  lib/schnorr.ak
  seedelf-cli/README.md
Labels: documentation

#29 setup is now in lib and not main
  seedelf-cli/src/commands/balance.rs
  seedelf-cli/src/commands/seedelf_all.rs
  seedelf-cli/src/commands/seedelf_new.rs
  seedelf-cli/src/commands/seedelf_remove.rs
  seedelf-cli/src/commands/sweep.rs
  seedelf-cli/src/commands/transfer.rs
  seedelf-cli/src/commands/wallet_info.rs
  seedelf-cli/src/lib.rs
  seedelf-cli/src/main.rs
  seedelf-cli/src/setup.rs
Labels: enhancement

#44 Readme review 02
  .github/workflows/release.yml
  README.md
  RELEASE.md
  seedelf-cli/Cargo.toml
  seedelf-cli/README.md
  seedelf-cli/src/display.rs
  seedelf-contracts/README.md
Labels: documentation

#45 Should be able to extract the label, clean it up, and display it
  seedelf-cli/src/data_structures.rs
  seedelf-cli/src/display.rs
  seedelf-cli/src/transaction.rs
  seedelf-cli/tests/address_test.rs
  seedelf-cli/tests/display_test.rs
Labels: enhancement

#47 46 add colors to display text
  seedelf-cli/Cargo.toml
  seedelf-cli/src/commands/balance.rs
  seedelf-cli/src/commands/create.rs
  seedelf-cli/src/commands/fund.rs
  seedelf-cli/src/commands/remove.rs
  seedelf-cli/src/commands/sweep.rs
  seedelf-cli/src/commands/transfer.rs
  seedelf-cli/src/commands/welcome.rs
  seedelf-cli/src/display.rs
  seedelf-cli/src/setup.rs
  seedelf-cli/src/web_server.rs
Labels: enhancement

#49 change utxo functionality test
  seedelf-cli/src/commands/transfer.rs
  seedelf-cli/tests/assets_test.rs
Labels: bug

#52 should build then upload and build the release notes
  .github/workflows/release.yml
Labels: bug, enhancement

#53 50 build bash one liner for quick install
  seedelf-cli/README.md
  seedelf-init.sh
Labels: enhancement

#56 54 add hashestxt for all checksums in release workflow
  .github/workflows/release.yml
  SECURITY.md
  seedelfwallet.asc
  support.asc
Labels: enhancement

#57 cleans up main
  .github/workflows/release.yml
  SECURITY.md
  seedelf-cli/README.md
  util/pubkeys/seedelfwallet.asc
  util/pubkeys/support.asc
  util/seedelf-init.sh
Labels: enhancement
